"use client";

import { useState } from "react";
import { RotateCcw } from "lucide-react";
import { api } from "@/lib/api";
import { Card, Button } from "@/components/ui";
import TopBar from "@/components/TopBar";
import { useMobileMenu } from "@/components/AppShell";
import { useToast } from "@/hooks/useToast";

export default function SettingsPage() {
  const openMenu = useMobileMenu();
  const { push } = useToast();
  const [resetting, setResetting] = useState(false);

  const resetDemo = async () => {
    if (!confirm("Reset all demo data? This replaces your current progress with the sample skill tree.")) return;
    setResetting(true);
    try {
      await api.post("/api/demo/reset");
      push({ title: "Demo data reset", lines: ["The sample skill tree has been restored."] });
      setTimeout(() => window.location.reload(), 800);
    } finally {
      setResetting(false);
    }
  };

  return (
    <>
      <TopBar title="Settings" subtitle="Application configuration and data" onMenu={openMenu} />
      <main className="px-4 md:px-8 py-6 max-w-2xl mx-auto space-y-4">
        <Card>
          <h2 className="text-sm font-medium text-ink mb-1">Demo Data</h2>
          <p className="text-xs text-ink-muted mb-4 leading-relaxed">
            SkillTree ships with a sample AI Engineer skill tree so the app isn't empty on first launch.
            This data belongs to a fictional demo user, not you — reset it any time to start fresh.
          </p>
          <Button variant="secondary" onClick={resetDemo} disabled={resetting}>
            <RotateCcw size={14} /> {resetting ? "Resetting..." : "Reset Demo Data"}
          </Button>
        </Card>

        <Card>
          <h2 className="text-sm font-medium text-ink mb-3">XP Rules</h2>
          <ul className="text-xs text-ink-muted space-y-2 font-mono">
            <li>30 min session → 10 XP (base rate)</li>
            <li>60 min session → 25 XP (base rate)</li>
            <li>Deep work bonus → +10%</li>
            <li>Daily consistency bonus → +5%</li>
            <li>Difficulty multiplier → Easy ×0.8, Medium ×1.0, Hard ×1.3</li>
          </ul>
          <p className="text-[11px] text-ink-faint mt-3">
            All XP is calculated server-side and is fully deterministic — never randomized.
          </p>
        </Card>

        <Card>
          <h2 className="text-sm font-medium text-ink mb-3">Level Formula</h2>
          <p className="text-xs text-ink-muted leading-relaxed">
            Cumulative XP to reach level N = 100 × (N−1) × N / 2. This produces the curve
            L1 = 0, L2 = 100, L3 = 250, L4 = 500, L5 = 800 XP, and so on — the same formula
            drives both individual skill levels and your overall account level.
          </p>
        </Card>

        <Card>
          <h2 className="text-sm font-medium text-ink mb-1">About</h2>
          <p className="text-xs text-ink-muted leading-relaxed">
            SkillTree v1.0.0 — Next.js, FastAPI, and SQLite. Recommendations are generated by a
            rule-based engine and require no external AI service.
          </p>
        </Card>
      </main>
    </>
  );
}
